Implementando função que filtra licitações com base nos empenhos já f…
analytics-ufcg/ta-de-pe-dados pull request #173
Opened 2021-09-09 03:17 UTC by felipesqra

…iltrados por covid19

2021-09-10 01:06 UTC, gileadekelvin requested changes
Massa @felipesqra! Ficou faltando atualizar o adaptador de licitações federais também?

2021-09-10 01:06 UTC, gileadekelvin commented on transformer/filters/filter_covid.R
> +  library(dplyr)
O import poderia estar no começo do arquivo e ser: ```library(tidyverse)```

2021-09-10 01:06 UTC, gileadekelvin commented on transformer/filters/filter_covid.R
> +  lics_f <- read_licitacoes_federal()
Poderia estar como parâmetro da função já que o `filter_licitacoes_federais_covid` será usado no adaptador de licitações.

2021-09-10 01:06 UTC, gileadekelvin commented on transformer/filters/filter_covid.R
> +      "modalidade_compra",
não precisa colocar a "modalidade_compra" só o "codigo_modalidade_compra" bastaria.

2021-09-10 01:06 UTC, gileadekelvin commented on transformer/filters/filter_covid.R
> +    copy = TRUE
Pra que serve esse `copy = TRUE`?

2021-09-10 01:27 UTC, felipesqra commented on transformer/filters/filter_covid.R
> +    copy = TRUE
@gileadekelvin, eu não estava conseguindo executar esse trecho do código, recebia uma erro informando que x e y, que são as duas tabelas, não estavam na mesma source. Pelo que pesquisei usar o 'copy = TRUE' cópia o y para a mesma source que x.

2021-09-10 01:29 UTC, felipesqra commented on transformer/filters/filter_covid.R
> +      "modalidade_compra",
> Massa @felipesqra! Ficou faltando atualizar o adaptador de licitações federais também?

@gileadekelvin , sim sim, como faz parte de outra task no taiga deixei pra abrir outra PR pra ela, tu acha melhor separar os PRs por etapas do planning?

2021-09-10 01:31 UTC, felipesqra commented
> Massa @felipesqra! Ficou faltando atualizar o adaptador de licitações federais também?

@gileadekelvin , sim sim, como faz parte de outra task no taiga deixei pra abrir outra PR pra ela, tu acha melhor separar os PRs por etapas do planning?

2021-09-18 17:09 UTC, gileadekelvin approved these changes

2021-09-18 17:10 UTC, merged