844 - Cria adaptador para itens de empenhos federais
analytics-ufcg/ta-de-pe-dados pull request #180
Opened 2021-09-20 18:11 UTC by emys-alb

2021-09-20 22:39 UTC, gileadekelvin requested changes

2021-09-20 22:39 UTC, gileadekelvin commented on transformer/adapter/estados/Federal/contratos/adaptador_itens_compra_federal.R
> +adapta_info_itens_compras_federal <- function(itens_compra_federal_df, empenhos_licitacao_df, filtro) {
Quem é empenhos_licitacao_df? Como obter esse dataframe?

2021-09-20 22:39 UTC, gileadekelvin commented on transformer/adapter/estados/Federal/contratos/adaptador_itens_compra_federal.R
> +    left_join(itens_compra_federal_df %>% select(nr_licitacao,
Não entendi muito bem o objetivo desse left_join. É com o próprio dataframe?

2021-09-20 22:39 UTC, gileadekelvin commented on transformer/adapter/estados/Federal/contratos/adaptador_itens_compra_federal.R
> +    )
O que acham de ter um select no final para deixar mais claro as colunas retornadas?

2021-09-20 22:40 UTC, gileadekelvin commented on transformer/adapter/estados/Federal/contratos/adaptador_itens_compra_federal.R
> +  POSTGRES_PASSWORD = 'secret'
Este bloco pode estar comentado

2021-09-20 22:48 UTC, gileadekelvin commented on transformer/adapter/estados/Federal/contratos/adaptador_itens_compra_federal.R
> +  POSTGRES_PASSWORD = 'secret'
A gente vai ter que depois pensar numa solução pra ter essas variáveis de ambiente configuradas no ambiente de desenvolvimento. Pra não ter que ficar comentando e descomentando.

2021-09-20 22:54 UTC, gileadekelvin commented on transformer/adapter/estados/Federal/contratos/adaptador_itens_compra_federal.R
> +    )
@emys-alb @felipesqra O retorno dos itens federais deve ter a mesma assinatura, isto é, as mesmas colunas de outros adaptadores como o de [Pernambuco](https://github.com/analytics-ufcg/ta-de-pe-dados/blob/master/transformer/adapter/estados/PE/contratos/adaptador_itens_contratos_pe.R#L26).

O que eu recomendo:
1. Executar o adaptador de pernambuco e identificar as colunas geradas
2. Adicionar um select no adaptador de pernambuco para deixar claro o retorno
3. Adicionar o mesmo select no adaptador dos itens federais

Opcional:
1. Revisar o PR que configura o ambiente de testes
2. Criar um arquivo de teste que avalia se o adaptador de itens federais retorna as exatas colunas definidas no select.

Qualquer dúvida estou a disposição!

2021-09-20 22:55 UTC, gileadekelvin commented on transformer/adapter/estados/Federal/contratos/adaptador_itens_compra_federal.R
> +adapta_info_itens_compras_federal <- function(itens_compra_federal_df, empenhos_licitacao_df, filtro) {
@emys-alb massa! com a nova documentação consegui executar de boas.

2021-09-20 23:02 UTC, emys-alb commented on transformer/adapter/estados/Federal/contratos/adaptador_itens_compra_federal.R
> +    left_join(itens_compra_federal_df %>% select(nr_licitacao,
Passou despercebido o significado na hora de reaproveitar, vou remover.

2021-09-20 23:03 UTC, gileadekelvin commented on transformer/adapter/estados/Federal/contratos/adaptador_itens_compra_federal.R
> +    left_join(itens_compra_federal_df %>% select(nr_licitacao,
Beleza!

2021-09-22 21:57 UTC, gileadekelvin approved these changes

2021-09-22 21:57 UTC, merged