fetch empenhos_relacionados
analytics-ufcg/ta-de-pe-dados pull request #213
Opened 2021-12-08 01:56 UTC by felipesqra

2021-12-11 19:38 UTC, gileadekelvin commented on transformer/processor/export_atualiza_contratos_bd.R
> +filtra_contratos_tem_alteracoes <- function(contratos_processados_df){
Poderíamos adicionar documentação nas funções desse arquivo

2021-12-11 19:43 UTC, gileadekelvin commented on transformer/processor/export_atualiza_contratos_bd.R
> +contratos_filtrados$codigo_contrato %>%
Ao invés de usar `contratos_filtrados$codigo_contrato` o que acha de usarmos o padrão do dplyr `contratos_filtrados %>% pull(codigo_contrato)` ?

2021-12-11 19:48 UTC, gileadekelvin commented on transformer/processor/export_atualiza_contratos_bd.R
> +write_csv2(empenhos_relacionados, "./data/empenhos.csv")
Poderíamos usar o pacote here para salvar o arquivo. Não entendi porque usar o write_csv2, acho que o write_csv é geralmente o padrão.

Ficaria algo como:
`write_csv(empenhos_relacionados, here::here("data/dados_federais/empenhos_documentos_relacionados.csv"))`

O que acha?

2021-12-11 19:50 UTC, gileadekelvin commented on transformer/processor/export_atualiza_contratos_bd.R
> +  map(fetch_documentos_relacionados_federais) %>%
Acredito que se usássemos a função map_dfr não precisaríamos da funçao gera_df_documentos_relacionados. O que você acha?

2021-12-11 19:53 UTC, gileadekelvin commented on transformer/processor/export_atualiza_contratos_bd.R
> +  map(fetch_documentos_relacionados_federais) %>%
Para obter uma coluna com o valor do empenho original que gerou a requisição poderíamos adicionar um mutate na funçao que baixa do site do portal de transparência.

Algo como:

```
  tryCatch({
    download.file(url, temp)
    dados <- read_csv2(temp)
    unlink(temp)
  }, error = function(e) {
    flog.info("Não foi possível realizar o download dos dados! Verifique se o download está disponível no Portal de Transparência")
    flog.error(e)
    return(tibble())
  })
  
  dados <- dados %>% 
    mutate(empenho_original = codigo)
```

2021-12-11 19:53 UTC, gileadekelvin requested changes
Vai ser preciso subir novamente o arquivo 
```sh
transformer/utils/fetcher/export_documentos_federais_relacionados.R
```

Mas acho que o nome: `fetcher_documentos_federais_relacionados.R` seria mais claro. O que acha?

2021-12-20 23:53 UTC, gileadekelvin commented on transformer/processor/export_atualiza_contratos_bd.R
> +  contratos_filtrados <- contratos_processados_df %>% filter(tem_alteracoes == TRUE & id_estado == 99) %>% head()
Podemos remover esse head() ?

2021-12-20 23:55 UTC, gileadekelvin commented on transformer/processor/export_atualiza_contratos_bd.R
> +  contratos_processados_df <- contratos_processados_df %>% filter(tem_alteracoes == FALSE | tem_alteracoes == TRUE & id_estado != 99)
Como essa atribuição está dentro do escopo da função, ela não vai atualizar o dataframe  contratos_processados_df no environment. 

O que acha de deixar esses comandos fora dessa função mesmo? acho que são simples o suficiente.

2021-12-20 23:59 UTC, gileadekelvin commented on transformer/processor/export_atualiza_contratos_bd.R
> +  contratos_processados_df <- contratos_processados_df %>% filter(tem_alteracoes == FALSE | tem_alteracoes == TRUE & id_estado != 99)
o que acha da linha 18 ser algo como:
```
demais_contratos <- contratos_processados_df %>% filter(!(id_contrato %in% (contratos_filtrados %>% pull(id_contrato))))
```

?

2021-12-21 00:02 UTC, gileadekelvin commented on transformer/processor/export_atualiza_contratos_bd.R
> +  filter(! duplicated(codigo_empenho_original))
Não entendi muito bem esse trecho:
```
group_by(codigo_empenho_original) %>%
  filter(! duplicated(codigo_empenho_original))
```

Seria para evitar duplicações?

2021-12-21 00:05 UTC, gileadekelvin commented on transformer/processor/export_atualiza_contratos_bd.R
> +contratos_filtrados <- contratos_filtrados %>%
Quando eu executei essa função, a quantidade de linhas do dataframe de contratos processados ficou diferente do dataframe atualizado com os novos valores. Acontece aí também?

2021-12-21 00:07 UTC, gileadekelvin commented on transformer/processor/export_atualiza_contratos_bd.R
> +contratos_filtrados <- contratos_filtrados %>%
No dataframe contratos_filtrados existem linhas com id repetido para o contrato.

2021-12-21 00:08 UTC, gileadekelvin commented on transformer/processor/export_atualiza_contratos_bd.R
> +  contratos_processados_df <- contratos_processados_df %>% filter(tem_alteracoes == FALSE | tem_alteracoes == TRUE & id_estado != 99)
Na verdade, do jeito que está o script essa linha 18 não está sendo necessária. Por causa do full join da linha 77.

2021-12-21 00:09 UTC, gileadekelvin requested changes
@felipesqra executei o script aqui e deu tudo certo com a amostra que peguei! Show! fiz alguns comentários de dúvidas que eu tive pra podermos ir ajustando.

2021-12-22 02:38 UTC, felipesqra commented on transformer/processor/export_atualiza_contratos_bd.R
> +  contratos_filtrados <- contratos_processados_df %>% filter(tem_alteracoes == TRUE & id_estado == 99) %>% head()
Simmmm Gile, foi algo que implementei para testar e acabei me esquecendo de remover, vou subir uma atualização sem ele

2021-12-22 02:42 UTC, felipesqra commented on transformer/processor/export_atualiza_contratos_bd.R
> +  contratos_processados_df <- contratos_processados_df %>% filter(tem_alteracoes == FALSE | tem_alteracoes == TRUE & id_estado != 99)
Não entendi porque ela não seria necessária Gile, o full join sem essa linha 18 não vai deixar algumas linhas duplicadas?

2021-12-22 02:44 UTC, felipesqra commented on transformer/processor/export_atualiza_contratos_bd.R
> +  filter(! duplicated(codigo_empenho_original))
Isso mesmo Gile. por ter feito o primeiro group_by, esse segundo é necessário ou posso remover?

2021-12-22 02:46 UTC, felipesqra commented on transformer/processor/export_atualiza_contratos_bd.R
> +contratos_filtrados <- contratos_filtrados %>%
Quanto aos ids repetidos, tu se refere ao data frame assim que é importado ou depois do processamento?

2021-12-22 02:47 UTC, felipesqra commented on transformer/processor/export_atualiza_contratos_bd.R
> +  contratos_filtrados <- contratos_processados_df %>% filter(tem_alteracoes == TRUE & id_estado == 99) %>% head()
sim sim Gile, passou despercebido

2021-12-23 15:03 UTC, closed without merging